[".config/fish/functions/fisher.fish"]
type = "file"
url = "https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish"
refreshPeriod = "168h"
[".hammerspoon/Spoons/SpoonInstall.spoon"]
type = "archive"
url = "https://github.com/Hammerspoon/Spoons/raw/master/Spoons/SpoonInstall.spoon.zip"
stripComponents = 1
refreshPeriod = "168h"
[".hammerspoon/Spoons/EmmyLua.spoon"]
type = "archive"
url = "https://github.com/Hammerspoon/Spoons/raw/master/Spoons/EmmyLua.spoon.zip"
stripComponents = 1
refreshPeriod = "168h"
[".config/bat/themes/Catppuccin-mocha.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Mocha.tmTheme"
refreshPeriod = "168h"
[".config/btop/themes/"]
type = "archive"
url = "https://github.com/catppuccin/btop/releases/download/1.0.0/themes.tar.gz"
refreshPeriod = "168h"
stripComponents = 1
["Library/Fonts/"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip"
refreshPeriod = "168h"
