when:
  - event: pull_request
    path: 'dot_flox/env/private_manifest.toml'

clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 0

steps:
  - name: version-check
    image: ghcr.io/flox/flox:latest
    commands:
      - bash .woodpecker/scripts/flox-version-check.sh
