[colors]
foreground = "#dcd7ba"
background = "#1f1f28"
cursor_bg = "#c8c093"
cursor_border = "#c8c093"
cursor_fg = "#c8c093"
selection_bg = "#2d4f67"
selection_fg = "#c8c093"

scrollbar_thumb = "#16161d"

ansi = [ "#090618", "#c34043", "#76946a", "#c0a36e", "#7e9cd8", "#957fb8", "#6a9589", "#c8c093" ]
brights = [ "#727169", "#e82424", "#98bb6c", "#e6c384", "#7fb4ca", "#938aa9", "#7aa89f", "#dcd7ba" ]
# If these are uncommented as they are in the original:
# https://github.com/rebelot/kanagawa.nvim/blob/master/extras/wezterm.lua
# they change the background colour and increase the size of the bar under
# the tab bar, which I don't really like. Removing these lines for now
# split = "#16161d"
# indexed = [ [16] = "#ffa066", [17] = "#ff5d62" ]
